- name: Configure snmp on all cisco ios switches
  hosts: cisco_ios_sw
  gather_facts: no
  vars:
    switches:
      - name: "switch1"
        snmp_community: "public"
        snmp_location: "Rack 1"
      - name: "switch2"
        snmp_community: "public"
        snmp_location: "Rack 2"
  tasks:
    - name: Configure SNMP on Cisco IOS switches
      ios_config:
        src: './snmp_template.j2'
    
    - name: Saving Configuration
      cisco.ios.ios_command:
        commands:
          - write memory
      register: write_output

    - name: Diplay SNMP status
      ansible.builtin.debug:
        var: write_output.stdout_lines[0]

    - name: Verify SNMP status after change
      cisco.ios.ios_command:
        commands:
          - show run | s snmp
      register: SNMP_Result
    
    - name: Display SNMP Configuration after change
      debug:
        var: SNMP_Result.stdout_lines